spring:
  application:
    name: mbti-world
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  sql:
    init:
      mode: always
      platform: mariadb
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 6000
      database: 2

## Logging
logging:
  level:
    org:
      springframework:
        cache: debug
      hibernate:
        sql: debug
        type: trace
